# Generated by Django 3.1.1 on 2020-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rewards', models.IntegerField()),
            ],
        ),
    ]
