# Generated by Django 3.1.1 on 2020-10-07 01:58

from django.db import migrations


def populate_db():
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
