# Generated by Django 3.1.1 on 2020-10-07 01:58

from django.db import migrations

from ..models import Account, Item


def populate_db(apps, schema_editor):
    MyModel = apps.get_model('backend', 'Account')

    file = open('backend/data/customer_list.csv', 'r')
    fileLines = file.readlines()
    for line in fileLines:
        accountInfo = line.split(',')
        account = MyModel.objects.all().create(
            firstName=accountInfo[0],
            lastName=accountInfo[1],
            email=accountInfo[2],
            phoneNumber=accountInfo[3],
            type=0,
            password='Password',
            balance=100,
            rewards=0,
        )
        account.save()

    file = open('backend/data/employee_list.csv', 'r')
    fileLines = file.readlines()
    for line in fileLines:
        accountInfo = line.split(',')
        theType = 0
        if accountInfo[2] == 'Cashier':
            theType = 1
        if accountInfo[2] == 'chef':
            theType = 2
        if accountInfo[2] == 'Manager':
            theType = 3
        account = MyModel.objects.all().create(
            firstName=accountInfo[0],
            lastName=accountInfo[1],
            email='',
            phoneNumber='',
            type=theType,
            password='Password',
            balance=100,
            rewards=0,
        )
        account.save()

    MyModel = apps.get_model('backend', 'Item')

    file = open('backend/data/inventory_list.csv', 'r')
    fileLines = file.readlines()
    for line in fileLines:
        itemInfo = line.split(',')
        item = MyModel.objects.all().create(
            name=itemInfo[0],
            stock=itemInfo[2],
            price=[3],
            category=itemInfo[1],
        )
        item.save()

    pass




class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_item_order_orderitem'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
