# Generated by Django 3.1.2 on 2020-11-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='itemID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
