# Generated by Django 3.1.2 on 2020-11-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_orderitem_itemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('itemInOrder', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fullItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.fullitem'),
            preserve_default=False,
        ),
    ]
